openapi: 3.0.0
info:
  description: This API provides audit info
  version: "1.0.0"
  title: Audit API
  contact:
    email: pariharjayant@yahoo.com
paths:
  /phlevel:
    get:
      summary: Gets ph level from history
      operationId: app.get_ph_level_readings
      description: Gets ph level from the event store
      parameters:
        - name: index
          in: query
          description: Gets ph level at the index in the event store
          schema:
            type: integer
            example: 100
      responses:
        '200':
          description: Successfully returned a ph level event
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/PHlevel'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                   message:
                     type: string
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                   message:
                     type: string
  /chlorinelevel:
    get:
      summary: gets chlorine level from history
      operationId: app.get_chlorine_level_readings
      description: gets chlorine level from the event store
      parameters:
        - name: index
          in: query
          description: gets chlorine level at the index in the event store
          schema:
            type: integer
            example: 100
      responses:
        '200':
          description: Successfully returned a chlorine level event
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/ChlorineLevel'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Not Found
components:
  schemas:
    PHlevel:
      required:
      - location
      - phlevel
      - temperature
      - device_id
      - timestamp
      - waterlevel
      type: object
      properties:
        location:
          type: string
          format: uuid
        waterlevel:
          type: number
          example: 12345
        temperature:
          type: number
          example: 12345
        device_id:
          type: number
          example: 12345
        phlevel:
          type: number
          example: 7
        timestamp:
          type: string
          format: date-time
          example: 2016-08-29T09:12:33.001Z
    ChlorineLevel:
      required:
      - chlorinelevel
      - location
      - temperature
      - device_id
      - timestamp
      - waterlevel
      type: object
      properties:
        location:
          type: string
          format: uuid
        waterlevel:
          type: number
          example: 12345
        temperature:
          type: number
          example: 12345
        device_id:
          type: number
          example: 12345
        chlorinelevel:
          type: number
          example: 7
        timestamp:
          type: string
          format: date-time
          example: 2016-08-29T09:12:33.001Z