---
openapi: 3.0.0
info:
  title: Swimming Pool Level
  description: Swimming pool level monitoring system to monitor level of Chlorine and PH in the water.It will be used by swimming pools located in community hall,hotels,apartment buildings and homes.
  version: "1.0"
servers:
- url: /
tags:
- name: devices
  description: Operations available to swimming pool level checking machine
paths:
  /phlevel:
    post:
      tags:
      - devices
      summary: reports the ph level of the pool
      description: adds a new ph level of the pool to the system
      operationId: app.report_ph_level
      requestBody:
        description: Reading added
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PHLevel'
      responses:
        "201":
          description: item added
        "400":
          description: invalid input, object invalid
    get:
      tags:
        - devices
      summary: gets ph level
      operationId: app.get_ph_level_readings
      description: Gets ph level added after a timestamp
      parameters:
        - name: timestamp
          in: query
          description: Limits the number of items on a page
          schema:
            type: string
            format: date-time
            example: 2016-08-29T09:12:33.001Z

        - name: end_timestamp 
          in: query
          description: Limits the number of items on a page
          schema: 
            type: string
            format: date-time
            example: 2016-08-29T09:12:33.001Z
      responses:
        '200':
          description: Successfully returned a ph level events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PHLevel'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /chlorinelevel:
    post:
      tags:
      - devices
      summary: reports the chlorine level of the pool
      description: adds a new chlorine level of the pool to the system
      operationId: app.report_chlorine_level
      requestBody:
        description: Reading added
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChlorineLevel'
      responses:
        "200":
          description: item added
        "400":
          description: invalid input, object invalid
    get:
      tags:
        - devices
      summary: gets chlorine level
      operationId: app.get_chlorine_level_readings
      description: Gets chlorine level added after a timestamp
      parameters:
        - name: timestamp
          in: query
          description: Limits the number of items on a page
          schema:
            type: string
            format: date-time
            example: 2016-08-29T09:12:33.001Z
            
        - name: end_timestamp 
          in: query
          description: Limits the number of items on a page
          schema: 
            type: string
            format: date-time
            example: 2016-08-29T09:12:33.001Z
      responses:
        '200':
          description: Successfully returned a list of chlorine level events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChlorineLevel'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
components:
  schemas:
    PHLevel:
      required:
      - location
      - phlevel
      - temperature
      - device_id
      - timestamp
      - waterlevel
      type: object
      properties:
        location:
          type: string
          format: uuid
        waterlevel:
          type: number
          example: 12345
        temperature:
          type: number
          example: 12345
        device_id:
          type: string
          example: 12345
        phlevel:
          type: number
          example: 7
        timestamp:
          type: string
          format: date-time
          example: 2016-08-29T09:12:33.001Z
    ChlorineLevel:
      required:
      - chlorinelevel
      - location
      - temperature
      - device_id
      - timestamp
      - waterlevel
      type: object
      properties:
        location:
          type: string
          format: uuid
        waterlevel:
          type: number
          example: 12345
        temperature:
          type: number
          example: 12345
        device_id:
          type: string
          example: 12345
        chlorinelevel:
          type: number
          example: 7
        timestamp:
          type: string
          format: date-time
          example: 2016-08-29T09:12:33.001Z
